---
title: "monthly_report_d"
author: "Asha Yadav"
date: "2/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rio)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(ggthemes)
library(colorblindr)

#install.packages('rsconnect')
library(rsconnect)
rsconnect::setAccountInfo(name='aashayadav',
			  token='AC782DCCCA5C1A8001B6DC76CBA07E00',
			  secret='r2L7iXjwdS7aOAbx9xV4hIoWH7H3ZrohaXv0INuv')
```


```{r, import data}
# loading data: files received from EC Cares

lane_monthly <- import(here("data", "Lane-monthly_report_data_Jan2015-Jan2021-1.xlsx")) %>%
  clean_names()

state_monthly <- import(here("data", "State-monthly_report_data_Jan2015-Jan2021-1.xlsx")) %>%
  clean_names()


```

```{r}
# Lane county monthly report- received from EC Cares 
# selected requied variables.
# separated month and year in two separate columns.
# removed line 74 as total of columns
# added a new column to specify it is lane county data.


lane_monthly <- lane_monthly %>%
  select("month", "ei_ref", "ec_ref", "ei_elig", "ec_elig", "ei_total_qual", "ecse_total_qual", "total_qual", "ei_total_exit", "ecse_total_exit", "total_exit", "ei_total_screen", "ecse_total_screen", "total_screen", "ei_total_eval", "ecse_total_eval", "total_eval") %>%
  separate("month", into = c("month", "year"), sep = " ")
  
lane_monthly = lane_monthly[-(74),]

lane_monthly$area <- rep("Lane county", nrow(lane_monthly)) # created a new column with area to specify lane county. 

#view(lane_monthly)

```

```{r}
# Oregon state monthly data- received from EC Cares 
# selected requied variables.
# separated month and year in two separate columns.
# removed line 74 as total of columns
# added a new column to specify it is Oregon data.

state_monthly <- state_monthly %>%
  select("month", "ei_ref", "ec_ref", "ei_elig", "ec_elig", "ei_total_qual", "ecse_total_qual", "total_qual", "ei_total_exit", "ecse_total_exit", "total_exit", "ei_total_screen", "ecse_total_screen", "total_screen", "ei_total_eval", "ecse_total_eval", "total_eval") %>%
  separate("month", into = c("month", "year"), sep = " ")

state_monthly = state_monthly[-(74),] 

state_monthly$area <- rep("Oregon", nrow(state_monthly)) # created a new column to specify a state data.
#view(state_monthly)

```

```{r}

# combined state and lanc county data 
# calculated total number of children under ei and ecse in lane county and oregon state.
monthly_report <- bind_rows(lane_monthly, state_monthly) %>%
   mutate(total_elig = ei_elig + ec_elig) %>%
   mutate(total_ref = ei_ref + ec_ref)
```


```{r}
# calculating total number of children by year and area by each query: 
# Query: Eligibility, Referrals, Evaluated, Qualify, Exit, Screen.

# Calculation total number of children in EI, ECSE and overall total by year and area.


d <- monthly_report %>%
  group_by(year, area) %>%
  summarize(ei_elig = sum(ei_elig),
            ec_elig = sum(ec_elig),
            total_elig = sum(total_elig),
            ei_ref = sum(ei_ref),
            ec_ref = sum(ec_ref),
            total_ref = sum(total_ref),
            ei_total_qual = sum(ei_total_eval),
            ecse_total_qual = sum(ecse_total_qual),
            total_qual = sum(total_qual),
            ei_total_exit = sum(ei_total_exit),
            ecse_total_exit = sum(ecse_total_exit),
            total_exit = sum(total_exit),
            ei_total_screen = sum(ei_total_screen),
            ecse_total_screen = sum(ecse_total_screen),
            total_screen = sum(total_screen),
            ei_total_eval = sum(ei_total_eval),
            ecse_total_eval = sum(ecse_total_eval),
            total_eval = sum(total_eval))

# Function to calculate sum as above. But doens't reduce number of lines of code so not used. Used curly curly from rlang. 

#d_sum <- function(data, var) {
#  data %>%
#    group_by(year, area) %>%
#    summarise(var = sum({{var}}))
#}



```

```{r}
# Export data_report in csv for Shiny. To test if function works with dataset

#rio::export(d, here("data", "d.csv"))

```


```{r}
# Step1: Function to create variables needed to anser client queries: Eligibility, Referrals, Evaluated, Qualify, Exit, Screen.
# Combined them into one data frame: "d_monthly_report".
d_col <- function(x, y, z) {
  d %>%
    group_by(year, area) %>%
    pivot_longer(cols = c(x, y, z),
                 names_to = "var",
                 values_to = "n") %>%
    ungroup() %>%
    select(year, area, var, n)
}

d_elig <- d_col("ei_elig", "ec_elig", "total_elig")
d_ref <- d_col("ei_ref", "ec_ref", "total_ref")
d_eval <- d_col("ei_total_eval", "ecse_total_eval", "total_eval")
d_exit <- d_col("ei_total_exit", "ecse_total_exit", "total_exit")
d_screen <- d_col("ei_total_screen", "ecse_total_screen", "total_screen")
d_qual <- d_col("ei_total_qual", "ecse_total_qual", "total_qual")

```


```{r}

# Joining all the datasets generated from the above function.
data_report <- bind_cols(d_eval, d_exit, d_qual, 
                              d_elig, d_ref, d_screen) %>%
  select(1:2, 3:4, 7:8, 11:12, 15:16, 19:20, 23:24) %>%
  rename(Year = year...1,
         Area = area...2,
         Evaluated = var...3,
         Count_eval = n...4,
         Exit = var...7,
         Count_exit = n...8,
         Qualify = var...11,
         Count_qual = n...12,
         Eligibility = var...15,
         Count_elig = n...16,
         Referrals = var...19,
         Count_ref = n...20,
         Screen = var...23,
         Count_screen = n...24)

```




```{r}

# Recoding ei_, ec_, total_ to EI, ECSE, TOTAL for table generation.
data_report$Eligibility = recode(data_report$Eligibility,
                                      "ei_elig" = "EI",
                                      "ec_elig" = "ECSE",
                                      "total_elig" = "TOTAL")

 data_report$Evaluated = recode(data_report$Evaluated,
                                      "ei_total_eval" = "EI",
                                      "ecse_total_eval" = "ECSE",
                                      "total_eval" = "TOTAL")
 
 data_report$Referrals = recode(data_report$Referrals,
                                      "ei_ref" = "EI",
                                      "ec_ref" = "ECSE",
                                      "total_ref" = "TOTAL")
 
 data_report$Exit = recode(data_report$Exit,
                                  "ei_total_exit" = "EI",
                                  "ecse_total_exit" = "ECSE",
                                  "total_exit" = "TOTAL")
 
 data_report$Screen = recode(data_report$Screen,
                                  "ei_total_screen" = "EI",
                                  "ecse_total_screen" = "ECSE",
                                  "total_screen" = "TOTAL")
 
 data_report$Qualify = recode(data_report$Qualify,
                                       "ei_total_qual" = "EI",
                                       "ecse_total_qual" = "ECSE",
                                       "total_qual" = "TOTAL")
 
 data_report
```

```{r}
# Export data_report in csv for Shiny.


#rio::export(data_report, here("data", "data_report.csv"))

```

```{r}

# Function to create plot with two variables such as 'Eligibility' and 'Count_elig'. BUT IT's NOT WORKING.
report_dataviz <- function(x, y) {
  
  plot <- data_report %>%
    ggplot(aes(Year, y)) +
    geom_line(aes(group = x), color= "grey80") +
    geom_point(aes(color = x)) + 
    facet_wrap(~Area) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5)) +
    labs(title = "Number of Children Eligible for EI & ECSE") +
    scale_y_continuous(expand = c(0, 0))
  ggplotly(plot)
}



 
```


```{r, function with three input variables}

# Function to generate plot from 

report_data_viz <- function(x, y, z) {
  
  plot <- d %>%
    group_by(year, area) %>%
    pivot_longer(cols = c(x, y, z),
                 names_to = "var",
                 values_to = "n") %>%
    select(year, area, var, n) %>%
    ggplot(aes(year, n)) +
    geom_line(aes(group = var), color= "grey80") +
    geom_point(aes(color = var)) + 
               facet_wrap(~area) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
    labs(title = "Number of Children Eligible for EI & ECSE") +
    scale_y_continuous(expand = c(0, 0))
  
  ggplotly(plot)

}

report_data_viz("ei_ref", "ec_ref", "total_ref")


```


```{r, plot1, Eligibility}
# Plot1: Number of Children Eligible for EI & ECSE
# Goals : eligible
# Number of kids eligible in EI (ei_elig)
# Number of kids eligible in ECSE (ec_elig)
# Total eligible EI/ECSE (created a new column to calculate total_elig)

d_eligibility<- data_report %>%
  ggplot(aes(Year, Count_elig)) +
  geom_line(aes(group = Eligibility), color= "grey80") +
  geom_point(aes(color = Eligibility)) + 
               facet_wrap(~Area) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Number of Children Eligible for EI & ECSE") +
  scale_y_continuous(expand = c(0, 0))
ggplotly(d_eligibility)

```

```{r}
data_report %>%
  select(Year, Area, Eligibility, Count_elig) %>%
  pivot_wider(names_from = Eligibility,
              values_from = Count_elig) %>%
  mutate(EI_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  mutate(ECSE_percent = round((ECSE/TOTAL)*100, digits = 2)) %>%
  kable()
  
```


```{r, plot2, Referrals}
#plot2: Number of Children Referred to EI & ECSE

# Goals : referrals
# Number of EI referrals (ei_ref)
# Number of ECSE referrals (ec_ref)
# Total number of referrals

d_referrals<- data_report %>%
  ggplot(aes(Year, Count_ref)) +
  geom_line(aes(group = Referrals), color= "grey80") +
  geom_point(aes(color = Referrals)) + 
               facet_wrap(~Area) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Number of Children Referred to EI & ECSE") +
  scale_y_continuous(expand = c(0, 0))
ggplotly(d_referrals)

```

```{r}
data_report %>%
  select(Year, Area, Referrals, Count_ref) %>%
  pivot_wider(names_from = Referrals,
              values_from = Count_ref) %>%
  mutate(EI_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  mutate(ECSE_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  kable()
```

```{r,plot3, Qualify}
# Goals : evaluated who qualify
# Number of EI children evaluated who qualify (ei_total_qual)
# Number of ECSE children evaluated who quality(ecse_total_qual)
# Total number of children evaluated who quality(total_qual)

d_qualify <- data_report %>%
  ggplot(aes(Year, Count_qual)) +
  geom_line(aes(group = Qualify), color= "grey80") +
  geom_point(aes(color = Qualify)) + 
               facet_wrap(~Area) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Number of Children Evaluated who Qualify for EI & ECSE") +
  scale_y_continuous(expand = c(0, 0))
ggplotly(d_qualify)

```

```{r}
data_report %>%
  select(Year, Area, Qualify, Count_qual) %>%
  pivot_wider(names_from = Qualify,
              values_from = Count_qual) %>%
  mutate(EI_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  mutate(ECSE_percent = round((ECSE/TOTAL)*100, digits = 2 )) %>%
  kable()
```

```{r, Exit}

# Goals: exit from services
# Number of EI children who exit from services(ei_total_exit)
# Number of ECSE children who exit from services (ecse_total_exit)
# Total number of children who exit from services (total_exit)

d_exit <- data_report %>%
  ggplot(aes(Year, Count_exit)) +
  geom_line(aes(group = Exit), color= "grey80") +
  geom_point(aes(color = Exit)) + 
               facet_wrap(~Area) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Number of Children who Exit from EI & ECSE") +
  scale_y_continuous(expand = c(0, 0))
  
ggplotly(d_exit)

```

```{r}
data_report %>%
  select(Year, Area, Exit, Count_exit) %>%
  pivot_wider(names_from = Exit,
              values_from = Count_exit) %>%
  mutate(EI_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  mutate(ECSE_percent = round((ECSE/TOTAL)*100, digits = 2)) %>%
  kable()

```

```{r, Screen}
# Goals: screened and not referred
# Number of EI children screened and not referred for evaluation (ei_total_screen)
# Number of ECSE children screened and not referred for evaluation (ecse_total_screen)
# Total number of children screened and not referred for evaluation (total_screen)
d_screen <- data_report %>%
  ggplot(aes(Year, Count_screen)) +
  geom_line(aes(group = Screen), color= "grey80") +
  geom_point(aes(color = Screen)) + 
               facet_wrap(~Area) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "No. of Children Screened & Not Referred for Evaluation") +
  scale_y_continuous(expand = c(0, 0))

ggplotly(d_screen)

```

```{r}
data_report %>%
  select(Year, Area, Screen, Count_screen) %>%
  pivot_wider(names_from = Screen,
              values_from = Count_screen) %>%
  mutate(EI_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  mutate(ECSE_percent = round((ECSE/TOTAL)*100, digits = 2)) %>%
  kable()
```

```{r, Evaluated}

# Goals: evaluated who did not quality
# Number of EI children evaluated who did not quality(ei_total_eval)
# Number of ECSE children evaluated who did not quality (ecse_total_eval)
# Total number of children evaluated who did not qualify(total_eval)

d_eval <- data_report %>%
  ggplot(aes(Year, Count_eval)) +
  geom_line(aes(group = Evaluated), color= "grey80") +
  geom_point(aes(color = Evaluated)) + 
               facet_wrap(~Area) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Number of Children Evaluated who Did Not Qualify") +
  scale_y_continuous(expand = c(0, 0))
  
ggplotly(d_eval)

```









```{r}
data_report %>%
  select(Year, Area, Evaluated, Count_eval) %>%
  pivot_wider(names_from = Evaluated,
              values_from = Count_eval) %>%
  mutate(EI_percent = round((EI/TOTAL)*100, digits = 2)) %>%
  mutate(ECSE_percent = round((ECSE/TOTAL)*100, digits = 2)) %>%
  kable()
```
```{r, tried_pyramid plot}
#install.packages("lemon")
library(lemon)

data_report_pyramid <- data_report %>%
  filter(Evaluated == "TOTAL") %>%
  select(Year, Area, Count_screen, Count_eval, 
         Count_exit, Count_qual, Count_elig, Count_ref)

names(data_report_pyramid)[names(data_report_pyramid) == "Count_elig"] <-
  "Eligibility"
names(data_report_pyramid)[names(data_report_pyramid) == "Count_screen"] <-
  "Screen"
names(data_report_pyramid)[names(data_report_pyramid) == "Count_exit"] <-
  "Exit"
names(data_report_pyramid)[names(data_report_pyramid) == "Count_qual"] <-
  "Qualify"
names(data_report_pyramid)[names(data_report_pyramid) == "Count_ref"] <-
  "Referral"
names(data_report_pyramid)[names(data_report_pyramid) == "Count_eval"] <-
  "Evaluated"

data_report_pyramid <- data_report_pyramid %>%
  pivot_longer(cols = "Screen":"Referral",
               names_to = "variable",
               values_to = "number")

# set variables as factor
data_report_pyramid[sapply(data_report_pyramid, is.character)] <- lapply(data_report_pyramid[sapply(data_report_pyramid,is.character)], as.factor)

data_report_pyramid

```

```{r}
# Export data_report_pyramid in csv for the overview table Shiny.

#rio::export(data_report_pyramid, here("data", "data_report_pyramid.csv"))

```

```{r, tried_pyramid plot}
ggplot(data = data_report_pyramid, 
       mapping = aes(x = ifelse(test = Area == "Lane county", 
                                yes = -number, 
                                no = number), 
                     y = variable, fill = Area)) +
  geom_col() +
  scale_x_symmetric(labels = abs) +
  labs(x = "number") +
  facet_wrap(~Year)

```



```{r, data table}

library(reactable)

data_pyramid_table <- data_report_pyramid %>%
  pivot_wider(names_from = "variable",
               values_from = "number") %>%
  group_by(Year) %>%
  reactable(height = 270,
            striped = TRUE,
            )
  



 # gt() %>%
 # tab_spanner(label = "Services",
         #     columns = vars("Screen", "Evaluated", "Exit", "Qualify", 
       #                      "Eligibility", "Referral")) %>%
 # cols_label(Area = " ") %>%
 # cols_align(align = "left", columns = vars(Area)) %>%
#  tab_header(title = "Number of Children",
      #       subtitle = "EC Cares Enrollment: 2015-2021") %>%
#  tab_options(row_group.background.color = "#B0E0E6")
  
  
  
#data_pyramid_table

```





```{r}
plot_overall <- data_report_pyramid %>%
  filter(Area == "Lane county") %>%
  ggplot(aes(reorder(variable, number), number, fill = Area)) +
  geom_col(width = 0.5) +
  coord_flip() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                     vjust = 1.0,
                                     hjust = 1.0),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none") +
  facet_wrap(~Year)
ggplotly(plot_overall)


  
```

